### PR TITLE
add unofficial venues request

### PR DESCRIPTION
**Pull request by jziggas**
Hi there. I added support for an api request which is not documented on stockfighter. It returns the list of venues available on the stock exchange.

### CODE REVIEW

**Comment by jescalan** [comment]
Hey, this is awesome, thank you! Could you just squash those commits together into one nice clean one, then I think we'd be good to merge :grinning:

**Comment by jziggas** [comment]
Done.

**Comment by jziggas** [comment]
I have a branch called 'websockets' on my fork where I have added additional features, including websockets and unofficial gamemaster endpoints. Not really used to writing ES6. Do you want to check it out, discuss the code offline, and maybe talk about where you see your repo going forward?

**Comment by jescalan** [comment]
@jziggas yeah absolutely, i was planning on adding websocket support but haven't had a chance to do so yet. Let me know when/how you want to chat about it and we can make it happen!

**Pull request merged**
